version: '3.3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'active_admin_sample:/var/lib/mysql'
volumes:
  active_admin_sample:
