version: '3.3'
services:
  dev-db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dev_db
    volumes:
      - 'rails_boilerplate_app:/var/lib/mysql'
volumes:
  rails_boilerplate_app:
