version: '3.3'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - 'active_admin_sample:/var/lib/postgresql/data'
volumes:
  active_admin_sample:
