version: '3.3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'rails_boilerplate_app:/var/lib/mysql'
volumes:
  rails_boilerplate_app:
